// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlvmHwAR_CdjvmVrH9_NGQngplqg9-I3Y',
    appId: '1:340022226838:web:b664a1ce340a5d963ef7b7',
    messagingSenderId: '340022226838',
    projectId: 'tugas-mobile-67672',
    authDomain: 'tugas-mobile-67672.firebaseapp.com',
    storageBucket: 'tugas-mobile-67672.firebasestorage.app',
    measurementId: 'G-GP6F01QP4Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkAhPJNqna2fksuUcEQ1lWsNZZYaYsjDw',
    appId: '1:340022226838:android:8234abb4fbd1e0713ef7b7',
    messagingSenderId: '340022226838',
    projectId: 'tugas-mobile-67672',
    storageBucket: 'tugas-mobile-67672.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJGWKh3XuR7oW1HFtdDVecg_lEYh4OWkQ',
    appId: '1:340022226838:ios:3fec2370841d94f13ef7b7',
    messagingSenderId: '340022226838',
    projectId: 'tugas-mobile-67672',
    storageBucket: 'tugas-mobile-67672.firebasestorage.app',
    iosBundleId: 'com.example.tugasMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJGWKh3XuR7oW1HFtdDVecg_lEYh4OWkQ',
    appId: '1:340022226838:ios:3fec2370841d94f13ef7b7',
    messagingSenderId: '340022226838',
    projectId: 'tugas-mobile-67672',
    storageBucket: 'tugas-mobile-67672.firebasestorage.app',
    iosBundleId: 'com.example.tugasMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlvmHwAR_CdjvmVrH9_NGQngplqg9-I3Y',
    appId: '1:340022226838:web:8f87d2f8863b48563ef7b7',
    messagingSenderId: '340022226838',
    projectId: 'tugas-mobile-67672',
    authDomain: 'tugas-mobile-67672.firebaseapp.com',
    storageBucket: 'tugas-mobile-67672.firebasestorage.app',
    measurementId: 'G-N9JRXV8D4H',
  );
}
